name: Deploy Development
on:
  push:
    branches:
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-develop:
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
    with:
      environment: development
      domain: dev.
